name: bokenka
favicon: null
layout_spectrum: 0.99754
typography_spectrum: 0.6902066483162344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 1
  lightness: 0.576896374579519
  saturation: 0.5559478420764208
  rhythmicContrast: 0.11999354418367147
purpose: []
