name: bokenka
favicon: null
layout_spectrum: 0.47787
typography_spectrum: 0.9123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f73c6'
    - '#ffffff'
    - '#66a1f1'
    - '#111717'
    - '#a2b060'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
